# Generated by Django 4.2.29 on 2026-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available for Work'), ('busy', 'Currently Busy'), ('partial', 'Limited Availability')], default='available', max_length=20)),
                ('message', models.CharField(blank=True, default='Open to freelance, teaching & collabs', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Availability Status',
            },
        ),
    ]
