# Generated by Django 4.2.29 on 2026-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_availabilitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
