# Generated by Django 4.2.29 on 2026-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('poem', 'Poem'), ('story', 'Story'), ('script', 'Script')], default='poem', max_length=20)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short preview shown on cards')),
                ('body', models.TextField(blank=True, default='')),
                ('year', models.CharField(blank=True, default='2024', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
